//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jimmov
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int Id { get; set; }
        public int intInfor { get; set; }
        public string FileName { get; set; }
        public string Pathname { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
    
        public virtual FlightInfor FlightInfor { get; set; }
    }
}
