//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jimmov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matach
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Uro { get; set; }
        public Nullable<double> Usa { get; set; }
        public Nullable<double> Shach { get; set; }
    }
}
