//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jimmov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightsEntities : DbContext
    {
        public FlightsEntities()
            : base("name=FlightsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coin> Coins { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<FlightInfor> FlightInfors { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<Matach> Mataches { get; set; }
        public virtual DbSet<TypeInfo> TypeInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
